# Generated by Django 2.2.6 on 2019-12-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyPoiRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, unique=True)),
                ('age', models.IntegerField(null=True)),
                ('DOB', models.DateField()),
                ('comments', models.CharField(max_length=255)),
                ('threat_level', models.CharField(choices=[('Choose threat level', 'Choose threat level'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Very High', 'Very High')], default='None', max_length=50)),
                ('image1', models.ImageField(upload_to='POI/uploads')),
                ('image2', models.ImageField(upload_to='POI/uploads')),
                ('image3', models.ImageField(upload_to='POI/uploads')),
                ('image4', models.ImageField(upload_to='POI/uploads')),
                ('image5', models.ImageField(upload_to='POI/uploads')),
                ('image6', models.ImageField(upload_to='POI/uploads')),
                ('image7', models.ImageField(upload_to='POI/uploads')),
                ('image8', models.ImageField(upload_to='POI/uploads')),
                ('image9', models.ImageField(upload_to='POI/uploads')),
                ('image10', models.ImageField(upload_to='POI/uploads')),
            ],
            options={
                'db_table': 'poirecord_mypoirecord',
            },
        ),
    ]
