# Generated by Django 2.2.6 on 2019-12-01 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('POI_Record', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCamera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CCID', models.CharField(max_length=20, unique=True)),
                ('Logitude', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Latitude', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'camera_mycamera',
            },
        ),
        migrations.CreateModel(
            name='MyCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'camera_mycity',
            },
        ),
        migrations.CreateModel(
            name='OnlineUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'camera_onlineuser',
            },
        ),
        migrations.CreateModel(
            name='MyZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Zone_area_name', models.CharField(max_length=255)),
                ('radius', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Latitude', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Logitude', models.DecimalField(decimal_places=2, max_digits=12)),
                ('CID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.MyCity')),
            ],
            options={
                'db_table': 'camera_myzone',
            },
        ),
        migrations.CreateModel(
            name='MyDetected_Poi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_image', models.ImageField(upload_to='')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=10)),
                ('cameraID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.MyCamera')),
                ('poiID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POI_Record.MyPoiRecord')),
            ],
            options={
                'db_table': 'camera_mydetected_poi',
            },
        ),
        migrations.AddField(
            model_name='mycamera',
            name='ZoneID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.MyZone'),
        ),
    ]
